# Install with pre-commit install && pre-commit install -t pre-push
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: master
    hooks:
    - id: check-executables-have-shebangs
    - id: debug-statements
    - id: check-merge-conflict
      stages: [push]
    - id: flake8
-   repo: https://github.com/python/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.7
- repo: local
  hooks:
  - id: hadolint
    name: Hadolint
    description: Haskell-based Docker image linter
    language: docker_image
    types:
      - dockerfile
    entry: --entrypoint /bin/hadolint hadolint/hadolint:latest --ignore DL3013 --ignore DL3018 --ignore DL3008 -
  -   id: tests
      name: run tests
      entry: pytest -v
      language: system
      types: [python]
      stages: [push]
