version: 2.1

orbs:
  shellcheck: circleci/shellcheck@1.0.0

jobs:
  hadolint:
      docker:
        - image: hadolint/hadolint:latest-debian
      steps:
        - run: apt update -y && apt install -y git
        - checkout
        - run: git ls-files --exclude='Dockerfile*' --ignored | xargs --max-lines=1 ${HADOLINT}
  black:
      docker:
        - image: unibeautify/black:latest
      steps:
        - checkout
        - run: black --check
  flake8:
    docker:
      - image: circleci/python:3.7
    steps:
      - run: sudo pip install flake8-black
      - checkout
      - run: flake8
  pytest:
    docker:
      - image: circleci/python:3.7
    steps:
      - run: sudo pip install pytest
      - checkout
      - run: ls && pytest .

workflows:
  version: 2.1
  lint:
    jobs:
      - shellcheck/check
      - hadolint
      - black
      - flake8
  test:
    jobs:
      - pytest
