version: 2.0

jobs:
  build:
      docker:
        - image: madkinszane/nextflow-ci:latest
      steps:

        # Download hadolint binary and set it as executable
        - run: |
          curl -sL -o ${HADOLINT} "https://github.com/hadolint/hadolint/releases/download/v1.16.0/hadolint-$(uname -s)-$(uname -m)"
          chmod 700 ${HADOLINT}

        # Download nextflow installer and run
        - run: curl -fsSL https://github.com/nextflow-io/nextflow/releases/download/v19.05.0-edge/nextflow | bash

        # Ensure linters are installed
        - run: pip install black flake8 flake8-black

        - checkout

        # Pass Docker files into HADOLINT
        - run: git ls-files --exclude='Dockerfile*' --ignored | xargs --max-lines=1 ${HADOLINT}

        # Check shell files with SHELLCHECK
        - run: bash -c 'shopt -s globstar; shellcheck **/*.{sh,ksh,bash}'

        # Check python files with flake8
        - run: flake8

workflows:
  version: 2.0
  build:
    jobs:
      - build

