version: 2.1

jobs:
  hadolint:
      docker:
        - image: hadolint/hadolint:latest
      steps:
        - checkout
        - run: git ls-files --exclude='Dockerfile*' --ignored | xargs --max-lines=1 ${HADOLINT}
  shellcheck:
      docker:
        - image: koalaman/shellcheck:latest
      steps:
        - checkout
        - run: bash -c 'shopt -s globstar; shellcheck **/*.{sh,ksh,bash}'
  black:
      docker:
        - image: unibeautify/black:latest
      steps:
        - checkout
        - run: black --check
  flake8:
    docker:
      - image: circleci:python:3.7
    steps:
      - run: pip install flake8-black
      - checkout
      - run: flake8

workflows:
  version: 2.1
  build:
    jobs:
      - shellcheck
      - hadolint
      - black
      - flake8
